### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function react-beautiful-dnd

### ISSUE THREAD

**Issue by kailashjakhar767** [atlassian/react-beautiful-dnd#2100]
```
Uncaught TypeError: Object(...) is not a function
    at connect.js:72
    at Object.<anonymous> (react-beautiful-dnd.esm.js:8208)
    at t (bootstrap b69cae7…:49)
    at Object.<anonymous> (main.959ff7be.js:94665)
    at t (bootstrap b69cae7…:49)
    at Object.<anonymous> (Table.js:1)
    at t (bootstrap b69cae7…:49)
    at Object.<anonymous> (main.959ff7be.js:20260)
    at t (bootstrap b69cae7…:49)
    at Object.<anonymous> (Routes.js:1)
    
```

As earlier it was working fine but now getting this issue after performing **npm install**
 
    I haven’t found any possible solution, Please help me out here.

**Comment by silentsilas** [comment]
I was also running into this issue. I believe it occurs when your project is importing a file that doesn't exist.
https://github.com/facebook/react/issues/14484

My guess is that react-beautiful-dnd is trying to import something that only exists in newer versions of React. Our issue was resolved after upgrading react and react-dom from 16.4.2 to 17.0.1. I'm not too great with project dependencies, but perhaps react-beautiful-dnd could also upgrade the versions in their package.json to prevent this occurring with future users?

**Comment by danieldelcore** [comment]
Hi @kailashjakhar767, can you please provide more information? Are you able to reproduce this issue in a [codesandbox](https://codesandbox.io/s/new) for me?
